### ISSUE TITLE
ValueError: time data '24:00' does not match format '%H:%M'

### ISSUE THREAD

**Issue by funks81** [MindrustUK/Heatmiser-for-home-assistant#179]
Had the same issue a few months ago - (unable to re-open!) which seemed to randomly fix itself - has been happening for the last 2 nights now.  Basically between 0000 and 0100 I have no data or control over my neostats - seems to be due to an incorrect time format somewhere - 24:00 instead of 00:00

2024-10-14 00:00:33.428 ERROR (MainThread) [custom_components.heatmiserneo] Unexpected error fetching neostat data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/heatmiserneo/__init__.py", line 41, in async_update_data
    _, devices_data = await hub.get_live_data()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/neohubapi/neohub.py", line 449, in get_live_data
    thermostats.append(NeoStat(self, thermostat))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/neohubapi/neostat.py", line 97, in __init__
    _time = datetime.strptime(self.time, "%H:%M")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '24:00' does not match format '%H:%M'

**Comment by MindrustUK** [comment]
@funks81 This issue seems to have happened to at least one other person recently. Normally this is related to daylight savings. This is fixed in the upstream neohubapi library, version >= 2. This is only in use in the dev branch. I'm still working on getting this completed and promoted to main. I suggest you switch to the dev branch and give it a go to see if that resolves your issue.

**Comment by funks81** [comment]
Thanks for getting back to me on this.  Apologies - but is there an idiots guide to downloading the dev branch (had a quick google and can't find anything useful).  Would all my thermostats need setting up again from scratch?
Thanks again

**Comment by MindrustUK** [comment]
Hi @funks81 The documentation is about the closest you can get:

https://github.com/MindrustUK/Heatmiser-for-home-assistant/tree/dev

It should be a case of copy - paste but if you run into issues follow up here and I'll see if I can help you out.

Yes, unfortunately thermostats will need setup again :/

**Comment by benkayuk** [comment]
Also suffering with this same error preventing the integration from initialising. I tried a full integration removal, and re-add, but not resolved. I can't figure out how to get onto the dev branch via HACS.

**Comment by MindrustUK** [comment]
@benkayuk What version of the integration are you running?

**Comment by benkayuk** [comment]
> @benkayuk What version of the integration are you running?

I'm not sure, I just added everything as per the instructions via HACS, so I presume I'm on "default" branch, which is now 1.5 as I understand it?

If I look in the integration settings though, it says Heatmiser 2.0.0 ?

**Comment by MindrustUK** [comment]
@benkayuk  2.0.0 is my fault I didn't update the manifest properly, I don't want to push it back as it may cause other problems. So it does seem you're up to date. When was the last time you saw this error? Was it after the update yesterday? Can you keep an eye on it and post logs if you see it again, as in theory the upstream fixes in the library should've resolved this a while back now.

**Comment by benkayuk** [comment]
> @benkayuk 2.0.0 is my fault I didn't update the manifest properly, I don't want to push it back as it may cause other problems. So it does seem you're up to date. When was the last time you saw this error? Was it after the update yesterday? Can you keep an eye on it and post logs if you see it again, as in theory the upstream fixes in the library should've resolved this a while back now.

Hi, I still have the error. I noticed it maybe 2 days ago, I tried a full HACS repository removal, integration removal and adding of everything back, but this has not resolved the issue.....

**Comment by MindrustUK** [comment]
When was the last time you saw this error?

**Comment by benkayuk** [comment]
> When was the last time you saw this error?

Right now, if I go to integrations page, the  integration says " ! Failed setup, will retry"

If I go into the integration, I see 

NEEDS ATTENTION
192.168.1.200:4242
1 device
! Failed setup, will retry: time data '255:00' does not match formate '%H:%M'

Now and again, it will flick to "initialising", then back to the same error above.

As I say, multiple restarts, and a full delete and reinstallation have not resolved the problem.

**Comment by MindrustUK** [comment]
Ahhhh this is a different issue! Might I direct you to... https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/176

Do you have any Neostat Air sensors per chance?

**Comment by benkayuk** [comment]
> Ahhhh this is a different issue! Might I direct you to... #176
> 
> Do you have any Neostat Air sensors per chance?

Aaaah sorry, I misread the title of this issue....yes I do have Air Sensors, in fact I added them over the weekend! 
I see there's no resolution on the other issue 176, other than trying dev branch....I can't work out how I swap to a different branch using HACS?

**Comment by MindrustUK** [comment]
I'm going to "at" you in the other thread @benkayuk and we'll continue there. I'm going to close this thread as the actual issue for this one was fixed ages ago in the upstream libray.
