### ISSUE TITLE
Update to 1.6 doesn't seem to stick

### ISSUE THREAD

**Issue by roddypratt** [MindrustUK/Heatmiser-for-home-assistant#209]
I see notification that update to 1.6 is available. Click "install" and then restart once install completes.

But after restart, HA still says that update to 1.6 is available - shows "installed version" as weird hex number.

![image](https://github.com/user-attachments/assets/9b9d9554-05f2-472b-8b22-11287e22d31a)

**Comment by funks81** [comment]
Yep - same problem here - have tried 3 times now - still says update available.

**Comment by roddypratt** [comment]
Tried removing devices/integration and reinstalling from scratch. Still the same (although that made my NeoAir V2's working again in HA!)

**Comment by MindrustUK** [comment]
It's to do with this feature: https://github.com/MindrustUK/Heatmiser-for-home-assistant/issues/208 I've built a release but for some reason HACS wants to pull from the latest commit on the default branch still. Couldn't figure out why in the time I allotted to this.

**Comment by XoneDB4** [comment]
Same issue here - thanks for picking up so quickly

**Comment by MindrustUK** [comment]
This should be resolved, credit once agian to @ocrease if someone can do some additional testing and confirm I can close this issue. Thanks!

**Comment by roddypratt** [comment]
Looks good to me. Update notification has magically disappeared.

**Comment by MindrustUK** [comment]
Thanks for confirming. Closing issue.

**Comment by schford** [comment]
Still broken for me- just updated it, restarted home assistant and it is saying update available.
![image](https://github.com/user-attachments/assets/811844a5-54d9-48d7-ba36-97a4325d8099)

**Comment by roddypratt** [comment]
I had that once more, but after hitting install it correctly showed installed version as 1.6.0 and hasn't reappeared.
