### ISSUE TITLE
After upgrade to v3.2.1 "Failed to set up" error

### ISSUE THREAD

**Issue by happy-chap** [MindrustUK/Heatmiser-for-home-assistant#294]
Hi, upgraded to v3.2.1 today (from v3.1.1) and am getting a "Failed to set up" error now in HA.

Error in the logs is:

```
Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 14:12:44 (1 occurrence)
Last logged: 14:12:44

Error setting up entry 192.168.66.12:4242 for heatmiserneo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/heatmiserneo/__init__.py", line 96, in async_setup_entry
    await _async_migrate_unique_ids(hass, entry)
  File "/config/custom_components/heatmiserneo/__init__.py", line 192, in _async_migrate_unique_ids
    device_registry.async_update_device(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        device_id=reg_device.id,
        ^^^^^^^^^^^^^^^^^^^^^^^^
        new_identifiers=new_identifiers,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        serial_number=None,
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 1135, in async_update_device
    added_identifiers = new_values["identifiers"] = self._validate_identifiers(
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        device_id, new_identifiers, False
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 1249, in _validate_identifiers
    raise DeviceIdentifierCollisionError(identifiers, existing_device)
homeassistant.helpers.device_registry.DeviceIdentifierCollisionError: Identifiers {('mac', '04:91:62:d6:91:bc')} already registered with DeviceEntry(area_id='kitchen', config_entries={'ec3be229e6616c92e5b817b0bc5c82f1'}, config_entries_subentries={'ec3be229e6616c92e5b817b0bc5c82f1': {None}}, configuration_url=None, connections=set(), created_at=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), disabled_by=<DeviceEntryDisabler.USER: 'user'>, entry_type=None, hw_version=None, id='d0641c50128c682bb1ae59b063058a33', identifiers={('mac', '04:91:62:d6:91:bc')}, labels=set(), manufacturer='Heatmiser', model='neoStat', model_id=None, modified_at=datetime.datetime(2025, 7, 28, 13, 8, 44, 144375, tzinfo=datetime.timezone.utc), name_by_user=None, name='Kitchen', primary_config_entry='ec3be229e6616c92e5b817b0bc5c82f1', serial_number=None, suggested_area=None, sw_version=None, via_device_id=None, is_new=False, _cache={'json_repr': b'{"area_id":"kitchen","configuration_url":null,"config_entries":["ec3be229e6616c92e5b817b0bc5c82f1"],"config_entries_subentries":{"ec3be229e6616c92e5b817b0bc5c82f1":[null]},"connections":[],"created_at":0.0,"disabled_by":"user","entry_type":null,"hw_version":null,"id":"d0641c50128c682bb1ae59b063058a33","identifiers":[["mac","04:91:62:d6:91:bc"]],"labels":[],"manufacturer":"Heatmiser","model":"neoStat","model_id":null,"modified_at":1753708124.144375,"name_by_user":null,"name":"Kitchen","primary_config_entry":"ec3be229e6616c92e5b817b0bc5c82f1","serial_number":null,"sw_version":null,"via_device_id":null}'})

```
Is the new discovery algorithm clashing with my existing setup? If I delete the integration and re-add it from scratch, I am going to cause a problem with my existing entities (ie. do they get renamed causing a problem with current automations and consistency of historical data reporting)?

Any help would be appreciated.

Thank-you.

**Comment by happy-chap** [comment]
Rather than delete the integration and re-add it, I downgraded back to v3.1.1 and it has mainly fixed the issue.

I do now have duplicate entities (which all say unavailable) of the real ones (which are working again) and I can obviously go through and delete the spurious entities that have been created.

**Comment by ocrease** [comment]
@happy-chap thanks for reporting this. I'll need to investigate. Would be useful if you can provide diagnostics output just in case.

**Comment by happy-chap** [comment]
Hi @ocrease, happy to, but just to make sure I understand, I assume to do that I need to enable debug logging _**but then also upgrade again to v3.2.1**_ so that it trap any errors, yes?

Just as a further piece of information, I spoke too soon when I said the downgrade to v3.1.1 had worked. Whilst it has restored functionality, it has changed the entities (presumably entity IDs) that are holding current information. Some of what I thought were the duplicate entities which reported as "unavailable" after the downgrade, it turns out are the entities that held the historic values - so I now have, for example, missing temperature data from my NeoAir monitors in my HA recorder.

**Comment by ocrease** [comment]
@happy-chap have a look at [diagnostics](https://mindrustuk.github.io/Heatmiser-for-home-assistant/faqs.html#diagnostics). Diagnostics from 3.1.1 should be OK for now.

Downgrading to a previous version is likely to throw some odd issues. I would suggest deleting the hub entry, restart HA and configuring it again (still on 3.1.1). Usually deleting the entries and re-adding does not break the history (but if that is very important, maybe take a backup first). If you get back to a good state after that, you could consider trying the upgrade again.

**Comment by happy-chap** [comment]
Thanks @ocrease. Diagnostics attached.

[config_entry-heatmiserneo-ec3be229e6616c92e5b817b0bc5c82f1.json](https://github.com/user-attachments/files/21476310/config_entry-heatmiserneo-ec3be229e6616c92e5b817b0bc5c82f1.json)

**Comment by robinheymans** [comment]
I'm experiencing the same issue after upgrading to 3.2.1. If I can be of any help, let me know!

**Comment by ocrease** [comment]
@robinheymans @happy-chap I assume both of you have been using the integration for a while. In a release last year (before I got involved) there was a breaking change, see the [20240928](https://github.com/MindrustUK/Heatmiser-for-home-assistant/blob/v3.2.1/docs/changelog.md#20240928) entry in the changelog. If you didn't do the recommended step of deleting the integration/entries, then I suspect your device entries are in a much older format than is supported by the migration done in v3.2.1.

The easiest solution is to delete the hub entry, restart HA and reconfigure, but I don't know if old history will be maintained. Any automations _should_ be OK, the entity ids haven't changed.

I will see if it's possible to support migration from those much older entities, but it will take a while. 

@robinheymans feel free to provide the exact error message you got and diagnostics so I can confirm that it is the same issue.

**Comment by robinheymans** [comment]
Been using it for a couple of years indeed! I'm gonna try and delete the hub and reconfigure. The exception I got is exactly the same as far as I can see:

```
Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: July 28, 2025 at 21:42:45 (3 occurrences)
Last logged: 13:30:59

Error setting up entry Heatmiser Neo Climate for heatmiserneo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/heatmiserneo/__init__.py", line 96, in async_setup_entry
    await _async_migrate_unique_ids(hass, entry)
  File "/config/custom_components/heatmiserneo/__init__.py", line 192, in _async_migrate_unique_ids
    device_registry.async_update_device(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        device_id=reg_device.id,
        ^^^^^^^^^^^^^^^^^^^^^^^^
        new_identifiers=new_identifiers,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        serial_number=None,
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 1135, in async_update_device
    added_identifiers = new_values["identifiers"] = self._validate_identifiers(
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        device_id, new_identifiers, False
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 1249, in _validate_identifiers
    raise DeviceIdentifierCollisionError(identifiers, existing_device)
homeassistant.helpers.device_registry.DeviceIdentifierCollisionError: Identifiers {('mac', '80:1f:12:4c:2b:64')} already registered with DeviceEntry(area_id='875e7df48dcf4c560e09ab8c71a3661d', config_entries={'9a4b6d04a60c4449a6b67252ce9be67e'}, config_entries_subentries={'9a4b6d04a60c4449a6b67252ce9be67e': {None}}, configuration_url=None, connections=set(), created_at=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), disabled_by=<DeviceEntryDisabler.USER: 'user'>, entry_type=None, hw_version=None, id='beaa0425fce87866af94bb97369d508d', identifiers={('mac', '80:1f:12:4c:2b:64')}, labels=set(), manufacturer='Heatmiser', model='neoStat', model_id=None, modified_at=datetime.datetime(2025, 7, 28, 19, 42, 45, 608, tzinfo=datetime.timezone.utc), name_by_user='Heatmiser Office Thermostat', name='Office', primary_config_entry='9a4b6d04a60c4449a6b67252ce9be67e', serial_number=None, suggested_area=None, sw_version=None, via_device_id=None, is_new=False, _cache={})
```

**Comment by ocrease** [comment]
@robinheymans thanks. Yes, that looks the same. The key thing is that the last line of the error shows `via_device_id=None`, which should only be the case for the hub itself, but in this case it was the `Office`. The fact a thermostat has an empty `via_device_id` is what makes me think it was set up before that 20240928 release when the link was introduced. The migration in v3.2.1 looks for the device that has it empty and treats it as the hub.

Did deleting and reconfiguring work for you? And did you lose history?

**Comment by bonkersbrains** [comment]
Same error, deleting the entities and readding worked perfectly though. It got the correct names on everything. I re-added using the local API connection option.

**Comment by ocrease** [comment]
@bonkersbrains thanks for the update. Did you check if you can see old history?

**Comment by bonkersbrains** [comment]
> [@bonkersbrains](https://github.com/bonkersbrains) thanks for the update. Did you check if you can see old history?

It seems to be all gone im afraid. Doesn't matter for my use case. But I can see that might be annoying.

**Comment by robinheymans** [comment]
Deleting and reconfiguring worked for me. I had to rename the entity id's again, but no big deal! The history seems to be gone as far as I can see, but that's no problem for me.

**Comment by s0upyd** [comment]
I deleted and re-added my hub and this has worked for me too. I didn't need to rename the entities, so I guess I used the suggestions for my entities originally. I've lost history but that's ok for me.

**Comment by ocrease** [comment]
Thanks @bonkersbrains @robinheymans @s0upyd  for confirming you manged to work around it by deleting and re-adding the hub. 

@happy-chap how did you get on? Have you managed to recover?

For anyone else who hits this issue, could you take a screenshot of the integration page where it shows the hub entry and the devices before you do the workaround above (delete and re-add the hub).

I still belive this issue will only affect users that were using the integration before 20240928 that didn't do the suggested step to delete and re-add the hub. The fix now is basically to do that step. 

As for losing the statistics, the temperature from climate entities is not stored in long term statistics anyway, so unless a user has specifically changed the HA recorder, the history only has the last 10 days I think. With that in mind, I'm not sure its even worth trying to produce a fix to get the history back. It will probably be gone by the time a fix is available.

**Comment by rob1303-hub** [comment]
> Thanks [@bonkersbrains](https://github.com/bonkersbrains) [@robinheymans](https://github.com/robinheymans) [@s0upyd](https://github.com/s0upyd) for confirming you manged to work around it by deleting and re-adding the hub.
> 
> [@happy-chap](https://github.com/happy-chap) how did you get on? Have you managed to recover?
> 
> For anyone else who hits this issue, could you take a screenshot of the integration page where it shows the hub entry and the devices before you do the workaround above (delete and re-add the hub).
> 
> I still belive this issue will only affect users that were using the integration before 20240928 that didn't do the suggested step to delete and re-add the hub. The fix now is basically to do that step.
> 
> As for losing the statistics, the temperature from climate entities is not stored in long term statistics anyway, so unless a user has specifically changed the HA recorder, the history only has the last 10 days I think. With that in mind, I'm not sure its even worth trying to produce a fix to get the history back. It will probably be gone by the time a fix is available.


@ocrease 

I haven't applied the fix yet.

A coupe of screenshots attached from Integrations page. Will not apply patch (delete and reinstall) yet.  Have removed some personal family names used as part of device names.  

Other information that may help: Have been using device in HA for a couple of years, from memory I cannot remember ever deleting and re-adding as per prior advice.  I have no problem losing history.

Happy to help on any way you need (may not be immediately responsive, as on holiday, but will try.

![Image](https://github.com/user-attachments/assets/33324dfe-2d5c-47e9-9aa9-e25e41e19445)
![Image](https://github.com/user-attachments/assets/65d01bb1-0d16-4b97-82fb-0212b2d192de)

**Comment by ocrease** [comment]
@rob1303-hub that's helpful thanks. If you can live with the errors for now, I have a few ideas of potential solutions and it would be great if you can try them out once/if I get them to work. Of course, if you need to be able to control your heating system via HA, feel free to delete and re-add the hub and you should be good to go

**Comment by rob1303-hub** [comment]
@ocrease - happy to help.
Let me know what you would like me to do.

**Comment by ocrease** [comment]
@rob1303-hub could you try v3.2.2-beta.1 (you have to use the redownload functionality in HACS). I have added some logic to detect this situation and now it raises an HA Issue which offers and automatic fix (which is to delete the old device entries). I have tested in on my test instance, but I can't test it on my proper instance since I don't have the issue.

Anyone else who hasn't done the suggested workaround already and wants to give it a go, feel free to try it and let me know how it went. 

The issue looks like this:

<img width="600" height="77" alt="Image" src="https://github.com/user-attachments/assets/bcd98937-db39-4668-9a13-50807a54a71d" />

<img width="415" height="234" alt="Image" src="https://github.com/user-attachments/assets/97473fd4-e6c1-4034-99ef-d17068bd34ae" />

**Comment by rob1303-hub** [comment]
> [@rob1303-hub](https://github.com/rob1303-hub) could you try v3.2.2-beta.1 (you have to use the redownload functionality in HACS). I have added some logic to detect this situation and now it raises an HA Issue which offers and automatic fix (which is to delete the old device entries). I have tested in on my test instance, but I can't test it on my proper instance since I don't have the issue.
> 
> Anyone else who hasn't done the suggested workaround already and wants to give it a go, feel free to try it and let me know how it went.

Will try now, and let you know what happens.

**Comment by rob1303-hub** [comment]
<img width="1173" height="373" alt="Image" src="https://github.com/user-attachments/assets/b0bbd4d9-ace5-48b7-a107-ec54af0078d4" />

Redownloaded and rebooted.  
This is the message I see.  Will work through now

**Comment by rob1303-hub** [comment]
<img width="595" height="530" alt="Image" src="https://github.com/user-attachments/assets/af0d31d1-d978-45cc-8997-40e4268107a4" />

**Comment by rob1303-hub** [comment]
<img width="820" height="496" alt="Image" src="https://github.com/user-attachments/assets/ff2e9c59-0e15-4eba-b799-8ea84f04b1c7" />


Will let you know if it is...

**Comment by ocrease** [comment]
Looks good so far. Would be interesting to see if you have old history too

**Comment by rob1303-hub** [comment]
<img width="1087" height="810" alt="Image" src="https://github.com/user-attachments/assets/1c9fd8a6-48c2-4219-b904-93de978ecba3" />

Will reboot and let you know if resolved

**Comment by rob1303-hub** [comment]
> Looks good so far. Would be interesting to see if you have old history too

Do you want me to check before I reboot?

**Comment by ocrease** [comment]
Actually I don't think a reboot is necessary

**Comment by ocrease** [comment]
> > Looks good so far. Would be interesting to see if you have old history too
> 
> Do you want me to check before I reboot?

I would say that if you need a reboot, it didn't work correctly. My aim was that it would fix and its done. Try holding off a reboot for now to see if you have any issues. 

And yeah you can check the history before.

**Comment by rob1303-hub** [comment]
<img width="1332" height="905" alt="Image" src="https://github.com/user-attachments/assets/0eaf9c31-5152-4c73-ae16-4d8f4f0cbdfe" />

Showing me current temp, but not a lot else (will look after reboot)

However, history until it broke appears to be available (I only keep a week of history in HA, extract what I need elsewhere).
<img width="826" height="607" alt="Image" src="https://github.com/user-attachments/assets/e37abc84-e6a0-4b83-8745-fe740c2c4203" />

**Comment by rob1303-hub** [comment]
Have not rebooted yet.

I do not look at these entities regularly (they turn on/off as needed per my HA configuration) so not sure if the blank Controls and Sensors are new or not.

**Comment by rob1303-hub** [comment]
> > > Looks good so far. Would be interesting to see if you have old history too
> > 
> > 
> > Do you want me to check before I reboot?
> 
> I would say that if you need a reboot, it didn't work correctly. My aim was that it would fix and its done. Try holding off a reboot for now to see if you have any issues.
> 
> And yeah you can check the history before.

Just wanted to say, thanks for all your work on this (I have no idea, other than using HA for the past 5 years - absolutely no skills).

Happy to be responsive to what you want me to do to help

**Comment by ocrease** [comment]
OK you have a lot of entities that don't exist anymore. You should go to the entities page, filter by the integration and by a status of "not provided". I bet you have quite a few. You should select all and delete them.

Entities are much more stable now, and in the future we can aim to clean any deprecated ones, but those are all quite old

**Comment by rob1303-hub** [comment]
Agreed I should make sure I maintain my entities more frequently (used to be much more attentive about this), as I said, I don't look at this integration that often as it was working.

Also going to say I have been busy at work ;-) but I will tell myself off (I am smiling and joking)

Thanks for your work on this

**Comment by ocrease** [comment]
I've released v3.2.2 as an actual release with this fix/solution

**Comment by alexhk90** [comment]
Thanks, @ocrease and @rob1303-hub. 
I hit the same issue with v3.2.1, and have also been using the integration for a while (certainly before the 20240928 release with the breaking change - I can't remember for certain if I had to remove and re-add the integration at the time, I think I might have just disabled the old entities or something along those lines). 
Once I get v3.2.2 through HACS, what do I need to do to fix it? Accept the "Found old devices" "Repair"?

**Comment by rob1303-hub** [comment]
>Once I get v3.2.2 through HACS, what do I need to do to fix it? Accept the "Found old devices" "Repair"?

that is all I had to do.

Did not delete need to delete the origial devices and then re-add.  They all come back with the prior names.


(Not withstanding that I had a load of really old entities, that I should have previously removed)

**Comment by alexhk90** [comment]
To confirm, I updated to v3.2.2 and accepted the "Repair" of "Found old devices" to clean up my old devices - this fixed the issue and even maintained the history of the entities (except for the time period when I was on v3.2.1 with my stale setup, of course). 
Thanks again!

**Comment by happy-chap** [comment]
Hi @ocrease, sorry I've been working away this week so was only able to look at this today.

Yes, I had been using the integration for quite a long time and I do vaguely remember the breaking change you mention in 20240928 release because I got the duplicate entries, but maybe I didn't fix them in the right way (maybe I just deleted them rather than deleting and readding the integration - I honestly can't remember now).

Anyway, I tried the latest version (thank-you @ocrease) and on the restart after updating to v3.2.2, I accepted the repair of the "found old devices" but then got the following error:

```
Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 18:00:54 (2 occurrences)
Last logged: 18:03:01

Error setting up entry 192.168.66.12:4242 for heatmiserneo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/heatmiserneo/__init__.py", line 103, in async_setup_entry
    await _async_migrate_unique_ids(hass, entry)
  File "/config/custom_components/heatmiserneo/__init__.py", line 191, in _async_migrate_unique_ids
    raise HomeAssistantError(
        f"Heatmiser Hub at {entry.data[CONF_HOST]}:{entry.data[CONF_PORT]} can't be configured because there are invalid devices"
    )
homeassistant.exceptions.HomeAssistantError: Heatmiser Hub at 192.168.66.12:4242 can't be configured because there are invalid devices
```

and thought I'd have to completely remove the integration and start again, but tried another restart first and got offered the repair a second time having "found old devices" again, and this appears to then allow the integration to start without error.

The only other issue for me, is that whist I still ended up with the same device names, each device had duplicate entities with half being "unavailable" due to "no longer being offered by the integration". I deleted all those, but also noticed that all the valid entites for each device had the dreaded "_2" added against them by HA. I've since corrected those as well.

So long story short, I am back up and running and many thanks for your help @ocrease.

Thanks, HC.

**Comment by ocrease** [comment]
@happy-chap the error you posted is expected, that also triggers the creation of the issue/repair.

From the sound of things your setup is quite corrupted now. I would suggest just deleting and re-adding the integration. You could leave it as is, but you are more likely to have issues in the future.

**Comment by ocrease** [comment]
@happy-chap by the way, you don't need to delete the integration, just the hub entry and reconfigure it. Shouldn't take long at all
